### ISSUE TITLE
saas flow v2

### ISSUE THREAD

**Issue by tanmoysrt** [frappe/press#2067]
Core changes for new saas flow has been merged https://github.com/frappe/press/pull/2018

**Required updates/fixes**
- [x] New Signup Field Type - Password (Need to be stored in encrypted way) https://github.com/frappe/press/pull/2068
- [x] Need to add some loading stuff at product trial signup page, as sometime api call takes some time. at that time it looks weird with blank app title and broken logo image #2075
- [x] Subscription Confirmation (step 4), needs to be "Subscription confirmation" to maintain the case. #2075 
- [x] On Fill details page, it shows sometimes empty section (after page refresh it become fixed).  Like this - 
![Screenshot 2024-08-16 at 2 15 36 PM](https://github.com/user-attachments/assets/eca247c6-2142-4bd6-88b9-73314216a1f8)
     #2075
- [x] Increase padding, or show it below?
       ![IMAGE 2024-08-16 18:38:36](https://github.com/user-attachments/assets/7079de8a-e6b0-45b2-a114-acab077c4eb9) #2075
- [x] User cannot log into existing site. 
       **Error -** No additional system user created for this site
       **Solution -** In FC new saas flow, check whether the site has any additional system user created. If there is no, go with `login with administrator` mode. #2075
- [x] Password strength verify #2075
- [x] Need to implement the authentication mechanism between site and FC for billing/checkout. #2077

**Comment by tanmoysrt** [comment]
All the sub-issues of this has been completed
